### ISSUE TITLE
Authentication errors should show the right status code

### ISSUE THREAD

**Issue by ashinzekene** [folucode/mock-league#1]
https://github.com/folucode/mock-league/blob/be6f912dab9fe1f02a31918b4983c30452f9a54c/src/middlewares/admin.js#L11

You should use the right status code for this. 401, I think

**Comment by folucode** [comment]
why I used 404 here is because as a regular user when you visit an admin-only page, it is set up show not found (as per the page doesn't exist). It only will be available to an admin user

**Comment by folucode** [comment]
I see what you're saying now. 401 which is "unauthorized" is a better status code.

I'm sorry, my bad. Thank You.
