### ISSUE TITLE
Sending response twice for cached data?

### ISSUE THREAD

**Issue by ashinzekene** [folucode/mock-league#3]
https://github.com/folucode/mock-league/blob/be6f912dab9fe1f02a31918b4983c30452f9a54c/src/routes/search.js#L10

Not sure but I think with the way you're checking for cached data, you'd get an error `Response already sent` if something is in the cache.

You could return the cached data instead

```js
const cachedData = checkCache(query)
if (cachedData) {
  res.json(cachedData);
  return;
}
```

**Comment by folucode** [comment]
You're correct. actually, the middleware already does the sending of the data if found in the cache, the issue is I don't return out of the function when it is done.

Fixed it below

```
if (data !== null) {
  res.send(JSON.parse(data));
  return; // return when cache data is found
} else {
  console.log('no');
  next();
}
```
