### ISSUE TITLE
Update only valid fields

### ISSUE THREAD

**Issue by ashinzekene** [folucode/mock-league#5]
https://github.com/folucode/mock-league/blob/be6f912dab9fe1f02a31918b4983c30452f9a54c/src/routes/user.js#L62

Instead of sending a crytic error message for this, you could instead get only the required updates. Pick only `["name", "email", "password"]` from the body and discard the others

**Comment by folucode** [comment]
Oh, yea, awesome suggestion. That way there won't be a need for the unnecessary checks and It would handle the request regardless of whatever is sent to the API.

**Comment by folucode** [comment]
```
const params = ({ name, email, password } = body);
const updates = Object.keys(params);
```

Fixed.
