### ISSUE TITLE
Others

### ISSUE THREAD

**Issue by ashinzekene** [folucode/mock-league#6]
Nice work. Other suggestions.
1. You could stick to a convention when returning responses. Something like
```js
{
  "message": string,
  "data": { whatever data you're sending }
  "success": boolean
}
```
2. Try implementing the [default express error handler](https://expressjs.com/en/guide/error-handling.html#the-default-error-handler) for catching unexpected errors

**Comment by folucode** [comment]
Thank you, would add these suggestions.
